import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { languages } from "../i18n/settings";
import { Header } from "./components/Header";
import { ImageSlider } from "./components/Slider";
import { Footer } from "./components/footer";
import { Auth } from "../modules/auth";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  return (
    <html lang={params?.lang} dir={params?.lang == "ar" ? "rtl" : "ltr"}>
      <body id='body' className={" flex flex-col"}>
        <Header lang={params?.lang} />
        <ImageSlider lang={params?.lang} />
        <>{children}</>
        <Footer lang={params?.lang} />
      </body>
    </html>
  );
}
